default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5

development:
  <<: *default
  database: celebrazil_development
  username: postgres
  password: password
  host:     localhost

test:
  <<: *default
  database: celebrazil_test
  username: postgres
  password: password
  host:     localhost

production:
  <<: *default
  database: dfps05km0ghugt
  username: gqbevguspxpgvp
  password: oziWsyykPdg2rmQSJcMN3_ddF2
  host:     ec2-54-83-5-43.compute-1.amazonaws.com
