default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5

development:
  <<: *default
  database: celebrazil_development
  username: postgres
  password: password
  host:     localhost

test:
  <<: *default
  database: celebrazil_test
  username: postgres
  password: password
  host:     localhost

production:
  <<: *default
  database: dfkk1aisocqhl6
  username: yuemnotkzwmvzg
  password: URWnBc9VsAY5ui9_FvFcSVs2fB
  host:     ec2-204-236-228-133.compute-1.amazonaws.com
